Implement Batch, Layer, Instance normalization
mlx-graphs/mlx-graphs pull request #163
Opened 2024-04-07 14:52 UTC by vinayhpandya

Added normalizations to improve stability of models during training
- Added batch Normalization to normalize features across batch
- Added layer normalization to normalize features across layers
- Added Instance normalization to normalize individual node features in a graph

## Proposed changes

Added normalizations to improve stability during training

## Checklist

Put an `x` in the boxes that apply.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

2024-04-07 18:28 UTC, francescofarina requested changes
Can you remove the types in the docstrings' args?

What do we think about naming these new layer using the `Normalization` keyword instead of `Norm`? Like `BatchNormalization`. I always felt that using norm is prone to mislead users.

2024-04-07 18:28 UTC, francescofarina commented on pyproject.toml
> +  "torch==2.2.0",
You need `torch_geometric` here

2024-04-08 16:54 UTC, francescofarina requested changes
I left a few extra comments.

It looks great overall - @TristanBilot what do you think about the naming of the normalization layers

2024-04-08 16:54 UTC, francescofarina commented on mlx_graphs/nn/norm/batch_norm.py
> +        affine (bool, optional): If set to :obj:`True`, this module has
rm type

2024-04-08 16:54 UTC, francescofarina commented on mlx_graphs/nn/norm/layer_norm.py
> +        eps (float, optional): A value added to the denominator for numerical
rm type

2024-04-08 16:54 UTC, francescofarina commented on mlx_graphs/nn/norm/batch_norm.py
> +        momentum: Optional[float] = 0.1,
A default value is provided, so this is not `Optional`

2024-04-08 16:54 UTC, francescofarina commented on mlx_graphs/nn/norm/layer_norm.py
> +        eps: Optional[float] = 1e-5,
A default value is provided, so this is not `Optional`

2024-04-09 00:31 UTC, TristanBilot requested changes
Very nice PR, just added few reviews!

2024-04-09 00:31 UTC, TristanBilot commented on mlx_graphs/nn/norm/instance_norm.py
> +            print("inside training")
can you remove print please

2024-04-09 00:31 UTC, TristanBilot commented on mlx_graphs/nn/norm/layer_norm.py
> +        mode: str = "graph",
would be better to have `Literal["graph", "node"] = "graph"` here

2024-04-09 00:31 UTC, TristanBilot commented on tests/nn/norm/test_batch_norm.py
> +    print(normalized_std)
rm

2024-04-09 00:31 UTC, TristanBilot commented on tests/nn/norm/test_batch_norm.py
> +    print(node_features.shape)
rm

2024-04-09 21:23 UTC, francescofarina approved these changes

2024-04-09 21:24 UTC, merged